import discord
from discord.ext import commands
import random
import time

description = 'Sebi Bot'

intents = discord.Intents.default()
intents.members = True

bot = commands.Bot(command_prefix='!', description=description, intents=intents)

@bot.event
async def on_ready():
    print(f'Logged in as {bot.user} (ID: {bot.user.id})')
    print('------')

@bot.command()
async def add(ctx, left: int, right: int):
    await ctx.send(left + right)

@bot.command()
async def roll(ctx, dice: str):
    try:
        rolls, limit = map(int, dice.split('d'))
    except Exception:
        await ctx.send('Format has to be in NdN!')
        return

    result = ', '.join(str(random.randint(1, limit)) for r in range(rolls))
    await ctx.send(result)

@bot.command(description='choose between multiple choises')
async def choose(ctx, *choices: str):
    await ctx.send(random.choice(choices))

@bot.command()
async def repeat(ctx, times: int, content='repeating...'):
    for i in range(times):
        await ctx.send(content)

@bot.command(name="fuck")
async def _foo(ctx, member: discord.Member):

    embed=discord.Embed(title="WelCUM to the Gulag u KEK :DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", description="Fak you my cok is biggah nigg--.. :DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD", color=0xff0000)
    embed.set_author(name="Your Mom", icon_url="https://pbs.twimg.com/profile_images/1298869320781574144/DEUhK05a.jpg")
    embed.set_thumbnail(url="https://pbs.twimg.com/profile_images/1298869320781574144/DEUhK05a.jpg")
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.add_field(name="AIDS FROM WISH", value="HAS YOUR MOM", inline=True)
    embed.set_footer(text="Why Are You Gay?")
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(60)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(60)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(60)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(60)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(60)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(60)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(60)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    time.sleep(0.02)
    await member.send(embed=embed)
    

@bot.command()
async def joined(ctx, member: discord.Member):
    await ctx.send(f'{member.name} joined in {member.joined_at}')

@bot.group()
async def cool(ctx):
    #says if a user is cool but actually just does if u use a sub command so u can trick ppl
    if ctx.invoked_subcommand is None:
        await ctx.send(f'No, {ctx.subcommand_passed} is not cool')

@cool.command(name='bot')
async def _bot(ctx):
    """Is the bot cool?"""
    await ctx.send('Yes, the bot is cool.')

bot.run('ODU4MTAwNTI5NDA2Mjc5Njkw.YNZOZA.Bv-KWNdQAk_7w1gg-zsWPMj9VcQ')
